[package]
name = "odintar"
version = "0.1.0"
edition = "2021"

description = "Library for manipulating Odin-flashable tar.md5 files"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[dependencies]
tar = "0.4"
md5 = "0.7"